package com.dsceksu.myelper.constants

object Constants {
    const val getStartedImages = "get_started_images"
    const val users = "users"
    const val orders = "orders"
    const val online = "online"
    const val productCategory = "product_categories"
    const val homeDisplay = "home_display"
    const val sponsored = "sponsored"
    const val userID = "userID"
    const val orderDeliveredPayment = "Order delivered payment"
    const val orderCancelRefund = "Order cancel refund"
    const val sponsoredProductPayment = "Sponsored product payment"
    const val sponsoredPostPayment = "Sponsored post payment"
    const val productPurchase = "Product Purchase"
    const val AdSlotPurchase = "Ad slot purchase"
    const val sponsoredPost = "sponsored_posts"
    const val productCategories = "product_categories"
    const val sponsoredProducts = "sponsored_product"
    const val recentlyViewedCategory = "recently_viewed_category"
    const val settlementAccount = "settlement_account"
    const val recentlyViewedProduct = "recently_viewed_products"
    const val products = "products"
    const val kycInfo = "kyc_info"
    const val wishlists = "wishlists"
    const val favouriteSellers = "favourite_sellers"
    const val wishlist = "Whishlists"
    const val active = "active"
    const val ads = "ads"
    const val seller = "seller"
    const val date = "date"
    const val productImages = "product_images"
    const val title = "title"
    const val pendingWithdrawal = "pending_withdrawal"
    const val favouriteSeller = "favourite_seller"
    const val carts = "carts"
    const val sellerReview = "Seller_Review"
    const val paymentInformation = "payment_info"
    const val noAvailableInStock = "noAvailableInStock"
    const val quantity = "quantity"
    const val shippingAddress = "shipping_address"
    const val ongoingOrder = "ongoing_order"
    const val recentlyViewedProducts = "recently_viewed_products"
    const val chats = "chats"
    const val time = "time"
    const val chatList = "chatlists"
    const val tokens = "Tokens"
    const val notification = "notifications"
    const val seen = "seen"
    const val rating = "rating"
    const val views = "views"
    const val followers = "followers"
    const val following = "following"
    const val paymentGatewayCred = "PaymentGatewayCred"
    const val flutterwave = "flutterwave"
    const val test = "test"
    const val live = "live"
    const val successful = "successful"
    const val cancel = "cancelled"
    const val completed = "completed"
    const val error = "error"
    const val transactions = "transactions"
    const val failed = "failed"
    const val revenue = "revenue"
    const val delivered = "delivered"
    const val completedOrders = "CompletedOrders"
    const val walletBalance = "wallet_balance"
    const val running = "running"
    const val homeAds = "home_ads"
    const val apiAuth = "Api_Auths"
    const val vtPass = "vtPass"

    //prefs
    const val username = "username"
    const val fullname = "fullname"
    const val email = "email"
    const val number = "number"
    const val banner = "banner"
    const val interstitial = "interstitial"
    const val rewarded = "rewarded"
    const val native = "native"

    //notification keys
    const val chat = "chat"


    //intents
    const val category = "category"
    const val isEdit = "is_edit"
    const val productID = "product_id"
    const val sellerID = "seller_id"
    const val isViewSellerProduct = "is_view_seller_product"
    const val isViewSellerService = "is_view_seller_service"
    const val recieverID = "receiver_id"
    const val isCreatePin = "is_create_pin"
    const val isLoginWIthPin = "is_login_with_pin"
    const val isUpdatePin = "is_update_pin"
    const val isSetNewPin = "is_set_new_pin"
    const val pin = "pin"
    const val lockAppWithPin = "lock_app_with_pin"
    const val pinPref = "pinPref"
    const val endTime = "endTime"

    //intets
    const val transactionsTitle = "transactionTitle"
    const val transactionID = "transactionID"
    const val productTitle = "productTitle"
    const val productImage = "productImage"
    const val amountSettled = "amountSettled"
    const val productPrice = "productPrice"
    const val sponsoredWeeks = "sponsoredWeeks"
    const val productQuantity = "productQuantity"
    const val postTitle = "postTitle"
    const val postContent = "postContent"
    const val postImage = "postImage"
    const val contactNumber = "contactNumber"
    const val contactEmail = "contactEmail"
    const val contactWebsite = "contactWebsite"
    const val slot = "slot"
    const val transactionDate = "transactionDate"
    const val productDeliveryCharge = "productDeliveryCharge"
    const val transactionAmount = "transactionAmount"
    const val transactionStatus = "transactionStatus"
    const val transactionMessage = "transactionMessage"
    const val transactionPaymentRef = "transactionPaymentRef"
    //
    const val alreadyAddedToCart = "View in cart"

    const val newSale = "newSale"
    const val orderStatus = "orderStatus"
    const val orderConfirmed = "orderConfirmed"
    const val newRating = "newRating"
    const val orderCancelled = "orderCancelled"
    const val newOrder = "newOrder"
    const val newProduct = "newProduct"
    const val productPayment = "Product payment"
    const val orderComplete = "Order complete"
    const val review = "Seller Review"
    const val reviews = "reviews"
    const val adsPayment = "Ads Payment"
    const val adsExpired = "Ads Expired"
    const val sponsoredProduct = "sponsored product"
    const val pendingWithdraw = "Pending Withdraw"
    const val paymentInfoChanged = "Payment info changed"

    //product categories
    const val phoneAndTablets = "Phones and Tablets"
    const val laptop = "Laptops"
    const val grocery = "Grocery"
    const val bookAndPQ = "Books and Pq"
    const val foodAndDrink = "Foods and Drinks"
    const val gaming = "Gaming"
    const val snacksAndCakes = "Snacks and Cakes"
    const val electronicsAndGadget = "Electronics and Gadgets"
    const val fashionAndClothing = "Fashion and Clothing"
    const val jwelleries = "Jewelleries"
    const val shoesAndFootwears = "Shoes and footwear"
    const val others = "Others"
    const val service = "Service"

    //values
    const val omesCharge = 5
    const val adsClickSuspendPeriod = 5
    const val paystackCharge = 3.0

    const val paybillsUrl = "https://play.google.com/store/apps/details?id=com.kineticdevelopers.billspaymentafrica"

    //codes
    const val oneO3 = "103"
    const val oneSeventeen = "117"
    const val oneEighteen = "118"
    const val oneTwentyOne = "121"
    const val oneTwentyTwo = "122"
    const val oneTwentyThree = "123"
    const val oneTwentySix = "126"
    const val oneTwentyEight = "128"
    const val oneTwentyFive = "125"
    const val oneThirty = "130"
    const val oneThirtyTwo = "132"
    const val oneThirtyFour = "134"
    const val oneThirtyFive = "135"
    const val oneThirtySeven = "137"
    const val oneThirtySix = "136"
    const val oneThirtyEight = "138"
    const val oneThirtyNine = "139"
    const val oneFourty = "140"
    const val oneFourtyOne = "141"
    const val oneFourtyTwo = "142"
    const val oneFourtyThree = "143"
    const val oneFourtySeven = "147"
    const val oneFourtyFive = "145"
    const val oneFourtyFour = "144"
    const val oneFourtySix = "146"
    const val oneFourtyEight = "148"
    const val oneTwenty = "120"
    const val oneFifty = "150"
    const val oneFiftyOne = "151"
    const val oneFiftyTwo = "152"
    const val oneFiftyThree = "153"
    const val oneFiftyFour = "154"
    const val oneFiftySix = "156"
    const val oneFiftySeven = "157"
    const val oneFiftyFive = "155"
    const val oneFiftyEight = "158"
    const val oneFiftyNine = "159"
    const val oneSixty = "160"
    const val oneSixtyOne = "161"
    const val oneSixtyTwo = "162"
    const val oneSixtyThree = "163"
    const val oneSixtyFour = "164"
    const val oneSixtyFive = "165"
    const val oneSixtySix = "166"
    const val oneSixtySeven = "167"
    const val oneSixtyEight = "168"
    const val oneSixtyNine = "169"
    const val oneSeventy = "170"
    const val oneSeventyOne = "171"
    const val oneSeventyTwo = "172"
    const val oneSeventyThree = "173"

}