package com.dsceksu.myelper.Models


class ProductModel(
    val category: String = "",
    val title: String = "",
    val description: String = "",
    val price: String = "",
    val cancelledPrice: String = "",
    val rating:Any ="",
    val id: String = "",
    val productID:String ="",
    val deliveryDays: String = "",
    val seller: String = "",
    val date: Any = "",
    val bookType:Any ="",
    val brand: String = "",
    val model: String = "",
    val backCamera:String ="",
    val condition: String = "",
    val noOfUsedDays: String = "",
    val anyFault: String = "",
    val whatIsInTheBox: String = "",
    val storage: String = "",
    val ram: String = "",
    val screenSize: String = "",
    val noAvailableInStock: String = "",
    val color: String = "",
    val withCase: String = "",
    val os: String = "",
    val resolution: String = "",
    val simSlot: String = "",
    val estimatedBatteryHour: String = "",
    val mainCamera: String = "",
    val frontCamera: String = "",
    val battery: String = "",
    val processorType: String = "",
    val storageType: String = "",
    val nafdacNo: String = "",
    val batteryType:String ="",
    val isbn: String = "",
    val author: String = "",
    val publisher: String = "",
    val year: String = "",
    val alcoholPercent: String = "",
    val sugarPercent: String = "",
    val ingredient: String = "",
    val mfgDate: String = "",
    val expiryDate: String = "",
    val containerType: String = "",
    val material: String = "",
    val clothSize: String = "",
    val isNewOrOkirika: String = "",
    val sizes:String = "",
    val is_approved: String = "",
    val deliveryCharge: String = "0",
    val imageLists:List<String>? = null,
    val status: String = "",
    val image: String = "",
    val sponsored:Boolean = false,
    val startDate:String ="",
    val endDate:String ="",
    val weeks:String =""
) {
}
